# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/amass/db/db_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .. import result_pb2 as protos_dot_amass_dot_result__pb2

from ..result_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/amass/db/db_message.proto',
  package='db',
  syntax='proto3',
  serialized_options=b'Z.github.com/kofeebrian/capamass/protos/amass/db',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n protos/amass/db/db_message.proto\x12\x02\x64\x62\x1a\x19protos/amass/result.proto\"\x1a\n\x08\x44\x42\x43onfig\x12\x0e\n\x06latest\x18\x01 \x01(\x08\"=\n\x08\x44\x42Result\x12\x16\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x06.Event\x12\x19\n\x07\x64omains\x18\x02 \x03(\x0b\x32\x08.Domains\"e\n\tDBRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x06\x64omain\x18\x02 \x01(\tH\x00\x88\x01\x01\x12!\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x0c.db.DBConfigH\x01\x88\x01\x01\x42\t\n\x07_domainB\t\n\x07_config\"V\n\nDBResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x06\x64omain\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1c\n\x06result\x18\x03 \x01(\x0b\x32\x0c.db.DBResultB\t\n\x07_domainB0Z.github.com/kofeebrian/capamass/protos/amass/dbP\x00\x62\x06proto3'
  ,
  dependencies=[protos_dot_amass_dot_result__pb2.DESCRIPTOR,],
  public_dependencies=[protos_dot_amass_dot_result__pb2.DESCRIPTOR,])




_DBCONFIG = _descriptor.Descriptor(
  name='DBConfig',
  full_name='db.DBConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latest', full_name='db.DBConfig.latest', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=93,
)


_DBRESULT = _descriptor.Descriptor(
  name='DBResult',
  full_name='db.DBResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='db.DBResult.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domains', full_name='db.DBResult.domains', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=156,
)


_DBREQUEST = _descriptor.Descriptor(
  name='DBRequest',
  full_name='db.DBRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='db.DBRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domain', full_name='db.DBRequest.domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='db.DBRequest.config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_domain', full_name='db.DBRequest._domain',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_config', full_name='db.DBRequest._config',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=158,
  serialized_end=259,
)


_DBRESPONSE = _descriptor.Descriptor(
  name='DBResponse',
  full_name='db.DBResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='db.DBResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domain', full_name='db.DBResponse.domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='db.DBResponse.result', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_domain', full_name='db.DBResponse._domain',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=261,
  serialized_end=347,
)

_DBRESULT.fields_by_name['events'].message_type = protos_dot_amass_dot_result__pb2._EVENT
_DBRESULT.fields_by_name['domains'].message_type = protos_dot_amass_dot_result__pb2._DOMAINS
_DBREQUEST.fields_by_name['config'].message_type = _DBCONFIG
_DBREQUEST.oneofs_by_name['_domain'].fields.append(
  _DBREQUEST.fields_by_name['domain'])
_DBREQUEST.fields_by_name['domain'].containing_oneof = _DBREQUEST.oneofs_by_name['_domain']
_DBREQUEST.oneofs_by_name['_config'].fields.append(
  _DBREQUEST.fields_by_name['config'])
_DBREQUEST.fields_by_name['config'].containing_oneof = _DBREQUEST.oneofs_by_name['_config']
_DBRESPONSE.fields_by_name['result'].message_type = _DBRESULT
_DBRESPONSE.oneofs_by_name['_domain'].fields.append(
  _DBRESPONSE.fields_by_name['domain'])
_DBRESPONSE.fields_by_name['domain'].containing_oneof = _DBRESPONSE.oneofs_by_name['_domain']
DESCRIPTOR.message_types_by_name['DBConfig'] = _DBCONFIG
DESCRIPTOR.message_types_by_name['DBResult'] = _DBRESULT
DESCRIPTOR.message_types_by_name['DBRequest'] = _DBREQUEST
DESCRIPTOR.message_types_by_name['DBResponse'] = _DBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DBConfig = _reflection.GeneratedProtocolMessageType('DBConfig', (_message.Message,), {
  'DESCRIPTOR' : _DBCONFIG,
  '__module__' : 'protos.amass.db.db_message_pb2'
  # @@protoc_insertion_point(class_scope:db.DBConfig)
  })
_sym_db.RegisterMessage(DBConfig)

DBResult = _reflection.GeneratedProtocolMessageType('DBResult', (_message.Message,), {
  'DESCRIPTOR' : _DBRESULT,
  '__module__' : 'protos.amass.db.db_message_pb2'
  # @@protoc_insertion_point(class_scope:db.DBResult)
  })
_sym_db.RegisterMessage(DBResult)

DBRequest = _reflection.GeneratedProtocolMessageType('DBRequest', (_message.Message,), {
  'DESCRIPTOR' : _DBREQUEST,
  '__module__' : 'protos.amass.db.db_message_pb2'
  # @@protoc_insertion_point(class_scope:db.DBRequest)
  })
_sym_db.RegisterMessage(DBRequest)

DBResponse = _reflection.GeneratedProtocolMessageType('DBResponse', (_message.Message,), {
  'DESCRIPTOR' : _DBRESPONSE,
  '__module__' : 'protos.amass.db.db_message_pb2'
  # @@protoc_insertion_point(class_scope:db.DBResponse)
  })
_sym_db.RegisterMessage(DBResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
