# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/amass/db/db_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import db_message_pb2 as protos_dot_amass_dot_db_dot_db__message__pb2
try:
  protos_dot_amass_dot_result__pb2 = protos_dot_amass_dot_db_dot_db__message__pb2.protos_dot_amass_dot_result__pb2
except AttributeError:
  protos_dot_amass_dot_result__pb2 = protos_dot_amass_dot_db_dot_db__message__pb2.protos.amass.result_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/amass/db/db_service.proto',
  package='db',
  syntax='proto3',
  serialized_options=b'Z.github.com/kofeebrian/capamass/protos/amass/db',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n protos/amass/db/db_service.proto\x12\x02\x64\x62\x1a protos/amass/db/db_message.proto23\n\tDBService\x12&\n\x03Run\x12\r.db.DBRequest\x1a\x0e.db.DBResponse\"\x00\x42\x30Z.github.com/kofeebrian/capamass/protos/amass/dbb\x06proto3'
  ,
  dependencies=[protos_dot_amass_dot_db_dot_db__message__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_DBSERVICE = _descriptor.ServiceDescriptor(
  name='DBService',
  full_name='db.DBService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=74,
  serialized_end=125,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='db.DBService.Run',
    index=0,
    containing_service=None,
    input_type=protos_dot_amass_dot_db_dot_db__message__pb2._DBREQUEST,
    output_type=protos_dot_amass_dot_db_dot_db__message__pb2._DBRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DBSERVICE)

DESCRIPTOR.services_by_name['DBService'] = _DBSERVICE

# @@protoc_insertion_point(module_scope)
