version: "3"

services:
  proxy:
    image: nginx:alpine
    ports:
      - 80:80 
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - backend

  app:
    image: capstone/cap-gateway
    build: .
    restart: unless-stopped
    depends_on:
      - amass-service
      - ffuf-service
      - zap-service
      - nmap-service
      - wapp-service
    expose:
      - 8000
    # For Testing
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    # End For Testing
    deploy:
      mode: replicatd
      replicas: 2

    networks:
      - backend
      - service

  amass-service:
    image: kofeebrian/amass-service:latest
    restart: unless-stopped
    networks:
      - service
    volumes:
      - amass-data:/data
      - amass-config:/.config/amass

  ffuf-service:
    image: boomboss555/ffuf-service:latest
    restart: unless-stopped
    networks:
      - service
    volumes:
      - ffuf-report:/code/app/reports

  zap-service:
    image: boomboss555/zap-service:latest
    restart: always
    expose:
      - 8000
    # command: zap.sh -daemon -host 0.0.0.0 -nostdout -silent & python3 main.py
    networks:
      - service
    volumes:
      - zap-report:/zap/wrk/app/reports

  wapp-service:
    image: kofeebrian/wapp-service:latest
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - service

  nmap-service:
    image: kofeebrian/nmap-service:latest
    restart: unless-stopped
    networks:
      - service
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.3"

  portainer:
      image: portainer/portainer-ce:latest
      container_name: portainer
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./portainer-data:/data
      ports:
        - 9000:9000

volumes:
  amass-data:
  amass-config:
  zap-wrk:
  zap-report:
  ffuf-report:

networks:
  frontend:
  backend:
    driver: bridge
  service:

