version: "3"

services:
  proxy:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - app
      - web
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - frontend
      - backend
      - service

  web:
    image: kofeebrian/cap-frontend:full
    restart: unless-stopped
    networks:
    - frontend
  app:
    image: kofeebrian/cap-gateway
    build: .
    restart: unless-stopped
    depends_on:
      - amass-service
      - ffuf-service
      - zap-service
      - nmap-service-1
      - nmap-service-2
      - nmap-service-3
      - wapp-service
    expose:
      - 8000
    volumes:
      - ./app:/app
    deploy:
      mode: replicatd
      replicas: 2

    networks:
      - backend
      - service

  amass-service:
    image: kofeebrian/amass-service:latest
    restart: unless-stopped
    networks:
      - service
    volumes:
      - amass-data:/data
      - amass-config:/.config/amass

  ffuf-service:
    image: boomboss555/ffuf-service:latest
    restart: unless-stopped
    networks:
      - service
    volumes:
      - ffuf-report:/code/app/reports

  zap-service:
    image: boomboss555/zap-service:latest
    restart: always
    expose:
      - 8000
    # command: zap.sh -daemon -host 0.0.0.0 -nostdout -silent & python3 main.py
    networks:
      - service
    volumes:
      - zap-report:/zap/wrk/app/reports

  wapp-service:
    image: kofeebrian/wapp-service:latest
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - service

  nmap-service-1:
    image: kofeebrian/nmap-service:ws
    restart: unless-stopped
    networks:
      - service
    deploy:
      resources:
        limits:
          cpus: "0.3"

  nmap-service-2:
    image: kofeebrian/nmap-service:ws
    restart: unless-stopped
    networks:
      - service
    deploy:
      resources:
        limits:
          cpus: "0.3"
  nmap-service-3:
    image: kofeebrian/nmap-service:ws
    restart: unless-stopped
    networks:
      - service
    deploy:
      resources:
        limits:
          cpus: "0.3"

volumes:
  amass-data:
  amass-config:
  zap-wrk:
  zap-report:
  ffuf-report:


networks:
  frontend:
  backend:
    driver: bridge
  service:


