# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/protos/amass/viz/viz_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.protos.amass.viz import viz_message_pb2 as app_dot_protos_dot_amass_dot_viz_dot_viz__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/protos/amass/viz/viz_service.proto',
  package='viz',
  syntax='proto3',
  serialized_options=b'Z/github.com/kofeebrian/capamass/protos/amass/viz',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&app/protos/amass/viz/viz_service.proto\x12\x03viz\x1a&app/protos/amass/viz/viz_message.proto2B\n\nVizService\x12\x34\n\rGetGraphistry\x12\x0f.viz.VizRequest\x1a\x10.viz.VizResponse\"\x00\x42\x31Z/github.com/kofeebrian/capamass/protos/amass/vizb\x06proto3'
  ,
  dependencies=[app_dot_protos_dot_amass_dot_viz_dot_viz__message__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_VIZSERVICE = _descriptor.ServiceDescriptor(
  name='VizService',
  full_name='viz.VizService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=87,
  serialized_end=153,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetGraphistry',
    full_name='viz.VizService.GetGraphistry',
    index=0,
    containing_service=None,
    input_type=app_dot_protos_dot_amass_dot_viz_dot_viz__message__pb2._VIZREQUEST,
    output_type=app_dot_protos_dot_amass_dot_viz_dot_viz__message__pb2._VIZRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIZSERVICE)

DESCRIPTOR.services_by_name['VizService'] = _VIZSERVICE

# @@protoc_insertion_point(module_scope)
