# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.protos.amass.viz import viz_message_pb2 as app_dot_protos_dot_amass_dot_viz_dot_viz__message__pb2


class VizServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGraphistry = channel.unary_unary(
                '/viz.VizService/GetGraphistry',
                request_serializer=app_dot_protos_dot_amass_dot_viz_dot_viz__message__pb2.VizRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_amass_dot_viz_dot_viz__message__pb2.VizResponse.FromString,
                )


class VizServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGraphistry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VizServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGraphistry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraphistry,
                    request_deserializer=app_dot_protos_dot_amass_dot_viz_dot_viz__message__pb2.VizRequest.FromString,
                    response_serializer=app_dot_protos_dot_amass_dot_viz_dot_viz__message__pb2.VizResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'viz.VizService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VizService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGraphistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/viz.VizService/GetGraphistry',
            app_dot_protos_dot_amass_dot_viz_dot_viz__message__pb2.VizRequest.SerializeToString,
            app_dot_protos_dot_amass_dot_viz_dot_viz__message__pb2.VizResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
