# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/protos/amass/enum/enum_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/protos/amass/enum/enum_message.proto',
  package='enum',
  syntax='proto3',
  serialized_options=b'Z0github.com/kofeebrian/capamass/protos/amass/enum',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(app/protos/amass/enum/enum_message.proto\x12\x04\x65num\"\xa5\x01\n\nEnumConfig\x12(\n\x04mode\x18\x01 \x01(\x0e\x32\x15.enum.EnumConfig.ModeH\x00\x88\x01\x01\x12\x14\n\x07timeout\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x14\n\x0c\x64nsResolvers\x18\x03 \x03(\t\",\n\x04Mode\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0b\n\x07PASSIVE\x10\x01\x12\n\n\x06\x41\x43TIVE\x10\x02\x42\x07\n\x05_modeB\n\n\x08_timeout\"[\n\x0b\x45numRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t\x12%\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x10.enum.EnumConfigH\x00\x88\x01\x01\x42\t\n\x07_config\"*\n\x0c\x45numResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\tB2Z0github.com/kofeebrian/capamass/protos/amass/enumb\x06proto3'
)



_ENUMCONFIG_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='enum.EnumConfig.Mode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PASSIVE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=151,
  serialized_end=195,
)
_sym_db.RegisterEnumDescriptor(_ENUMCONFIG_MODE)


_ENUMCONFIG = _descriptor.Descriptor(
  name='EnumConfig',
  full_name='enum.EnumConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='enum.EnumConfig.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='enum.EnumConfig.timeout', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dnsResolvers', full_name='enum.EnumConfig.dnsResolvers', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENUMCONFIG_MODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_mode', full_name='enum.EnumConfig._mode',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_timeout', full_name='enum.EnumConfig._timeout',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=51,
  serialized_end=216,
)


_ENUMREQUEST = _descriptor.Descriptor(
  name='EnumRequest',
  full_name='enum.EnumRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='enum.EnumRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domain', full_name='enum.EnumRequest.domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='enum.EnumRequest.config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_config', full_name='enum.EnumRequest._config',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=218,
  serialized_end=309,
)


_ENUMRESPONSE = _descriptor.Descriptor(
  name='EnumResponse',
  full_name='enum.EnumResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='enum.EnumResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domain', full_name='enum.EnumResponse.domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=353,
)

_ENUMCONFIG.fields_by_name['mode'].enum_type = _ENUMCONFIG_MODE
_ENUMCONFIG_MODE.containing_type = _ENUMCONFIG
_ENUMCONFIG.oneofs_by_name['_mode'].fields.append(
  _ENUMCONFIG.fields_by_name['mode'])
_ENUMCONFIG.fields_by_name['mode'].containing_oneof = _ENUMCONFIG.oneofs_by_name['_mode']
_ENUMCONFIG.oneofs_by_name['_timeout'].fields.append(
  _ENUMCONFIG.fields_by_name['timeout'])
_ENUMCONFIG.fields_by_name['timeout'].containing_oneof = _ENUMCONFIG.oneofs_by_name['_timeout']
_ENUMREQUEST.fields_by_name['config'].message_type = _ENUMCONFIG
_ENUMREQUEST.oneofs_by_name['_config'].fields.append(
  _ENUMREQUEST.fields_by_name['config'])
_ENUMREQUEST.fields_by_name['config'].containing_oneof = _ENUMREQUEST.oneofs_by_name['_config']
DESCRIPTOR.message_types_by_name['EnumConfig'] = _ENUMCONFIG
DESCRIPTOR.message_types_by_name['EnumRequest'] = _ENUMREQUEST
DESCRIPTOR.message_types_by_name['EnumResponse'] = _ENUMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnumConfig = _reflection.GeneratedProtocolMessageType('EnumConfig', (_message.Message,), {
  'DESCRIPTOR' : _ENUMCONFIG,
  '__module__' : 'app.protos.amass.enum.enum_message_pb2'
  # @@protoc_insertion_point(class_scope:enum.EnumConfig)
  })
_sym_db.RegisterMessage(EnumConfig)

EnumRequest = _reflection.GeneratedProtocolMessageType('EnumRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENUMREQUEST,
  '__module__' : 'app.protos.amass.enum.enum_message_pb2'
  # @@protoc_insertion_point(class_scope:enum.EnumRequest)
  })
_sym_db.RegisterMessage(EnumRequest)

EnumResponse = _reflection.GeneratedProtocolMessageType('EnumResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENUMRESPONSE,
  '__module__' : 'app.protos.amass.enum.enum_message_pb2'
  # @@protoc_insertion_point(class_scope:enum.EnumResponse)
  })
_sym_db.RegisterMessage(EnumResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
